name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Prepare release notes
        id: release-notes
        uses: hypengw/appstream-release-notes-action@v0.1.0
        with:
          file: release.xml
          version: ${{ github.ref_name }}

      - name: Publish immutable release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: ${{ steps.release-notes.outputs.path }}
          immutableCreate: true
          tag: ${{ github.ref_name }}
